<?php
/**
 * @package   Checkout_Placeholder
 * @copyright Copyright 2022 (c) mediarox UG (haftungsbeschraenkt) (http://www.mediarox.de)
 * @author    Marcus Bernt <mbernt@mediarox.de>
 */
?>
<style>
    .checkout-index-index .fieldset.address .field:not(.choice) .label {
        display: none;
    }
    .checkout-index-index .fieldset.address .field:not(.choice) .label::before {
        display: none;
    }
    .checkout-index-index .fieldset.address .field:not(.choice) .label::after {
        display: none;
    }
    #customer-email-fieldset label:not(.choice) {
        display: none;
    }
    div.field[class*="comment"] .label {
        display: none;
    }
</style>
